version: '3.9'
services:
  mysql:
    image: 'mysql:8.0.23'
    container_name: mysql-dev
    ports:
      - "3306:3306"
    volumes:
      - mysql-volume:/var/lib/mysql/data
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: evento

volumes:
  mysql-volume: